name: cutdce
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.7
  - numpy<2
  - scipy
  - pandas
  - pillow
  - pip:
      - beautifulsoup4
      - dominate
      - GPUtil
      - matplotlib
      - openpyxl
      - opencv-python
      - packaging
      - requests
      - scikit-image
      - SimpleITK
      - tqdm
      - visdom
